services:
  app:
    profiles: [ "dotnet" ]
    build:
      context: .
      dockerfile: Dockerfile.local
      args:
        BASE_IMAGE: mocking-monitor:latest
    container_name: box.app
    ports:
      - "8080:8080"
    dns:
      - 172.18.0.253
    depends_on:
      dns:
        condition: service_started
      entry:
        condition: service_started
      postgres:
        condition: service_started
      servicebus:
        condition: service_started
      entra:
        condition: service_healthy
    environment:
      # These environment variables should match what your app expects
      - ASPNETCORE_URLS=http://+:8080
      - DB_HOST=my-app.postgres.database.azure.com
      - SERVICEBUS_HOST=my-namespace.servicebus.windows.net
      - IDENTITY_AUTHORITY=https://login.microsoftonline.com/10000000-0000-4000-a000-000000000000/v2.0
    networks:
      infra-shared-net:
        ipv4_address: 172.18.0.5
