services:
  app:
    profiles: [ "dotnet" ]
    build:
      context: .
      dockerfile: Dockerfile.local
      args:
        APP_IMAGE: ${APP_IMAGE}
    container_name: box.app
    env_file:
      - path: .env
        required: false
    ports:
      - "8080:8080"
    dns:
      - 172.18.0.253
    depends_on:
      dns:
        condition: service_started
      entry:
        condition: service_started
      postgres:
        condition: service_started
      servicebus:
        condition: service_started
      entra:
        condition: service_healthy
    networks:
      infra-shared-net:
        ipv4_address: 172.18.0.5
