ARG APP_IMAGE
FROM ${APP_IMAGE}

COPY certs/dev-root-ca.crt /usr/local/share/ca-certificates/it-local-ca.crt
RUN apt-get update && apt-get install -y ca-certificates && \
    update-ca-certificates && \
    rm -rf /var/lib/apt/lists/*
